### ISSUE TITLE
Microsoft Azure Active Directory refuses redirect uri containing queries (/openid/doAuthenticationt%3Fprovider%3Dmicrosoft)

### ISSUE THREAD

**Issue by gepowy** [leibniz-psychology/openid#13]
**Describe the bug**
when attempting to use Microsoft Azure Active Directory, the error page is displayed:
We're unable to complete your request

invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application.

That is because the Redirect URI, even when written with %3F instead of ?, is not accepted by Microsoft as it contains a query.
In fact when entering in Azure a Redirect URI with a ?, it is not accepted with the error  "Failed to update [application] application. Error detail: URL may not contain a query string. [rRJ6I+7bLmbwbPteGB/Dy3] 

**What application are you using?**
 OJS version 3.3.0.8, plugin version 3.3.0.7

**Comment by RBoelter** [comment]
Hi @gepowy,
thanks for reporting. 
I fixed this issue and will push the new version to the OJS plugin gallery asap.
