### ISSUE TITLE
Log in using OpenID

### ISSUE THREAD

**Issue by gepowy** [leibniz-psychology/openid#16]
I do not understand if there is an issue with the plugin. When I register using an OpenID provider it creates an account and everything seems to work. When I log out and then try to log in (not register, the account already exists) using the same OpenID provider and credentials I'm asked if I have an account already or I'm new to the journal (just like when registering). 
As the account already exists with the same credentials, I think the correct beahviour should be for the system to just log me in.
Furthermore, if I select that I already have an account, the system asks for username and password, but if I use the same password used in OpenID it tells me it is invalid, and does not let me leave it blank.
Not sure if all this is a bug or just an issue that I don't understand how it should work.
Thank you for your help and for a great plugin!

**Comment by RBoelter** [comment]
I'm sorry but I can't replicate this issue.
I have tested it with ORCID and a custom provider.
- Login with ORCID -> perform ORCID login -> I am new to the journal -> fill in registration form -> submit.
- Logout
- Login with ORCID as in the step before -> after the ORCID login I was redirected directly to the user profile I created before.

**Comment by gepowy** [comment]
I tried again in a clean browser and using ORCID as you did, and I still have the issue. You can try on my installation at journal.rmbs.org

**Comment by gepowy** [comment]
Interesting: if I create an account not using Oauth and then use the Oauth to add other credentials to the same account (selecting I already have an account and entering the original login information (user name and password) created without Oauth) then it works (I can login either using the user name and password or Oauth). 
BTW in the same way I can add different OAuth providers (I set up an account to which I can log into with OJS credentials, google or microsoft).
So it seems the issue is when OpenID/Oauth is used to create a new account.
Hope this helps

**Comment by RBoelter** [comment]
I tried it on your journal and I see that it doesn't work, but I really don't know why because it works on so many other journals and I tested it again with OJS 3.3.0-3 - 3.3.0-8. Do you have access to the server logs? If so, it might help to check what exactly happens during the registration process.

**Comment by gepowy** [comment]
yes, I do have complete access to the server. Which logs should I look at? I suspect it is something related to the database (mysql  Ver 15.1 Distrib 10.5.12-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2) as it works when merging into a legacy (no Oauth/OpenID account)?

**Comment by RBoelter** [comment]
Usually the OJS logs are located in /var/log/apache2/error.log (on Ubuntu, may differ on Debian).
The easiest way is to type `tail -f /var/log/apache2/error.log` on the server and start an OpenID login in the browser.
Select the "I'm new to the journal " option, enter your data and submit. The server terminal displays the logs, so that you can see if any PHP errors occur during this process.

**Comment by gepowy** [comment]
This is logged when I finish the registration:

[Fri Nov 05 07:26:47.024066 2021] [proxy_fcgi:error] [pid 1916999:tid 140138722719488] [client 35.134.237.58:50011] AH01071: Got error 'PHP message: PHP Warning:  array_shift() expects parameter 1 to be array, object given in /var/www/public_html/journal/lib/pkp/classes/core/PKPRouter.inc.php on line 485', referer: https://journal.rmbs.org/index.php/BiomedSciInstrum/openid/doAuthentication?provider=google&code=4%2F0AX4XfWgjGKs1LstoiJLGyxZpBBOgPUk1oZ4gvvO1EXnT2HLjJ5lRhujgL8fiYbkEOFtfDA&scope=email+profile+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile&authuser=0&prompt=none

This when I log out from the account just created

[Fri Nov 05 07:27:52.844793 2021] [proxy_fcgi:error] [pid 1916999:tid 140138714326784] [client 35.134.237.58:50024] AH01071: Got error 'PHP message: PHP Warning:  array_shift() expects parameter 1 to be array, object given in /var/www/public_html/journal/lib/pkp/classes/core/PKPRouter.inc.php on line 485', referer: https://journal.rmbs.org/index.php/BiomedSciInstrum/openid/registerOrConnect

these similar 2 where from your attempt earlier this morning

[Fri Nov 05 04:52:36.296028 2021] [proxy_fcgi:error] [pid 1915196:tid 140138546472704] [client 136.199.1.50:12292] AH01071: Got error 'PHP message: PHP Warning:  array_shift() expects parameter 1 to be array, object given in /var/www/public_html/journal/lib/pkp/classes/core/PKPRouter.inc.php on line 485', referer: https://journal.rmbs.org/index.php/BiomedSciInstrum/openid/doAuthentication?provider=orcid&code=j3pg0D

[Fri Nov 05 04:53:01.085540 2021] [proxy_fcgi:error] [pid 1915196:tid 140138596828928] [client 136.199.1.50:55915] AH01071: Got error 'PHP message: PHP Warning:  array_shift() expects parameter 1 to be array, object given in /var/www/public_html/journal/lib/pkp/classes/core/PKPRouter.inc.php on line 485', referer: https://journal.rmbs.org/index.php/BiomedSciInstrum/user/profile

**Comment by gepowy** [comment]
This is when I create an account without using OpenID/Oauth

[Fri Nov 05 07:33:07.983523 2021] [proxy_fcgi:error] [pid 1916999:tid 140138722719488] [client 35.134.237.58:58422] AH01071: Got error 'PHP message: PHP Warning:  array_shift() expects parameter 1 to be array, object given in /var/www/public_html/journal/lib/pkp/classes/core/PKPRouter.inc.php on line 485', referer: https://journal.rmbs.org/index.php/BiomedSciInstrum/management/settings/access

and this is when I confirm the account

[Fri Nov 05 07:36:14.553162 2021] [proxy_fcgi:error] [pid 1916999:tid 140138714326784] [client 35.134.237.58:1929] AH01071: Got error 'PHP message: PHP Notice:  Only variable references should be returned by reference in /var/www/public_html/journal/lib/pkp/classes/security/AccessKeyDAO.inc.php on line 76'

this is when I combine an Oauth with the same non-Oauth account

[Fri Nov 05 07:37:47.320613 2021] [proxy_fcgi:error] [pid 2044750:tid 140138722719488] [client 35.134.237.58:58451] AH01071: Got error 'PHP message: PHP Warning:  array_shift() expects parameter 1 to be array, object given in /var/www/public_html/journal/lib/pkp/classes/core/PKPRouter.inc.php on line 485', referer: https://journal.rmbs.org/index.php/BiomedSciInstrum/openid/doAuthentication?provider=google&code=4%2F0AX4XfWj63lrHnQMn3BC7vVNoKT8_YiMlrlhX0T4t3rB8thd2O_noxBAjjGGpgLgS-uH7Yg&scope=email+profile+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&authuser=0&prompt=none

and this is when I log out from the combined account

[Fri Nov 05 07:38:13.753610 2021] [proxy_fcgi:error] [pid 1670559:tid 140138680755968] [client 35.134.237.58:58458] AH01071: Got error 'PHP message: PHP Warning:  array_shift() expects parameter 1 to be array, object given in /var/www/public_html/journal/lib/pkp/classes/core/PKPRouter.inc.php on line 485', referer: https://journal.rmbs.org/index.php/BiomedSciInstrum/openid/registerOrConnect

and this is when I log out 

[Fri Nov 05 07:40:31.965723 2021] [proxy_fcgi:error] [pid 1916999:tid 140138722719488] [client 35.134.237.58:58484] AH01071: Got error 'PHP message: PHP Warning:  array_shift() expects parameter 1 to be array, object given in /var/www/public_html/journal/lib/pkp/classes/core/PKPRouter.inc.php on line 485', referer: https://journal.rmbs.org/index.php/BiomedSciInstrum/user/profile

**Comment by gepowy** [comment]
I think this is you just trying to log in agan

[Fri Nov 05 07:40:21.350789 2021] [proxy_fcgi:error] [pid 1670559:tid 140138680755968] [client 136.199.1.50:20420] AH01071: Got error 'PHP message: Guzzle Exception thrown: Client error: `POST https://oauth2.googleapis.com/token` resulted in a `400 Bad Request` response:\n{\n  "error": "invalid_grant",\n  "error_description": "Bad Request"\n}\nPHP message: PHP Warning:  array_shift() expects parameter 1 to be array, object given in /var/www/public_html/journal/lib/pkp/classes/core/PKPRouter.inc.php on line 485', referer: https://github.com/leibniz-psychology/openid/issues/16

**Comment by RBoelter** [comment]
These array_shift() warnings are really annoying, but not the reason why it doesn't work properly.

**Comment by gepowy** [comment]
If it can be helpful, I have the actual database transaction logs for a similar cycle of tests. I can send them to the email you used for the test registration if that would be useful (the file is about 800KB)

**Comment by RBoelter** [comment]
have you access to the db? the openid plugin settings are saved in the table user_settings:

![image](https://user-images.githubusercontent.com/7657717/140522899-77345056-4d4d-4ac9-97c9-fe4dc592db57.png)

**Comment by RBoelter** [comment]
Each user registered via the OpenId plugin should have at least one openid::\<provider\> entity in this table.

**Comment by gepowy** [comment]
here is the table contents for yours and mine test accounts. Note that my test account was created merging google Oauth with an existing account created not using Oauth (which works then with Oauth). Yours, created just via Oauth doesn't have an openid::

26	en_US	affiliation	0	0	ZPID	string
26	en_US	familyName	0	0	Boelter	string
26	en_US	givenName	0	0	Ronny	string
32		openid::google	256	0	103446435220837776481	string
32		orcid	0	0		string
32	en_US	affiliation	0	0	VT	string
32	en_US	familyName	0	0	Pagnacco	string
32	en_US	givenName	0	0	Guido	string

**Comment by RBoelter** [comment]
Hmm, interesting. Now I'm a bit confused. I will check this on Monday. I really have no idea why the user data is not updated with the openid settings in your journal.

**Comment by gepowy** [comment]
yes, it is strange. Thanks for all your help. Have a nice weekend

**Comment by gepowy** [comment]
Quick update: today I tried with a clean installation of OJS (new database and new download of the OJS code), and the same issue exists.

**Comment by RBoelter** [comment]
I did exactly the same this morning and for me it works. Fresh OJS 3.3.0-8 and OpenId Plugin Version from my GH Repo. My Server is running on Ubuntu 18.04. Do you use a default Theme? Or maybe a missing PHP Module? If you use the files from my Github repository, you have to run `composer install` in the plugin folder.

**Comment by gepowy** [comment]
Ubuntu 20.04.3 LTS, PHP 7.4.25, Apache/2.4.51, OJS 3.3.0.8. I originally installed the OpenId plugin from OJS Plugin Library, and then edited the files with the changes since #12. Running composer on OJS lib/pkp and the plugin returns "Nothing to install, update or remove".
I'm attaching printouts of the OJS system information and PHP information as well as the list of PHP modules installed.
[PHP 7.4.25 - phpinfo().pdf](https://github.com/leibniz-psychology/openid/files/7497969/PHP.7.4.25.-.phpinfo.pdf)
[php_modules.txt](https://github.com/leibniz-psychology/openid/files/7497971/php_modules.txt)
[System Information Open Journal Systems.pdf](https://github.com/leibniz-psychology/openid/files/7497972/System.Information.Open.Journal.Systems.pdf)

**Comment by RBoelter** [comment]
Hmm ok, the modules seem to be ok. One last try: Could you remove the openid plugin from /plugins/generic/openid and install the folder from the attached .tar.gz? Those are the exact files I used this morning for the fresh installation. If that doesn't help, I'll have to ask the PKP folks if anyone has an idea, because the plugin works on an OJS we use in production, and also on other OJS installations. The problem is that I can't debug something that works on my servers. I am sorry.

[openid.tar.gz](https://github.com/leibniz-psychology/openid/files/7498397/openid.tar.gz)

**Comment by gepowy** [comment]
Not sure what you did, or what the issue was, but it works perfectly now. It also solves #18!
Thank you, thank you, thank you!

**Comment by RBoelter** [comment]
You're welcome, I'm glad I could finally solve your problem :-)
I will put a new version in the PKP plugin gallery in the next few days, which will include all the changes regarding to the other closed issues. So you can update the plugin via the gallery in the future.
