### ISSUE TITLE
Import ORCID id when creating account using ORCID OpenID

### ISSUE THREAD

**Issue by gepowy** [leibniz-psychology/openid#18]
**Describe the problem you would like to solve**
When creating an account using ORCID OpenID the ORCID ID is not imported/set. User has to go to profile and manually import it

**Describe the solution you'd like**
Users expect the ID to be imported as they have created the account using ORCID

**Who is asking for this feature?**
Users, system administrators, editors

**Comment by RBoelter** [comment]
It will be importet if the setting "[Enable OpenID provider user data synchronization](https://github.com/leibniz-psychology/openid/wiki/Advanced-Settings#enable-openid-user-details-synchronization)" is active:
![image](https://user-images.githubusercontent.com/7657717/140496351-ed92a333-90e2-4774-8017-9d00f18ce653.png)

**Comment by gepowy** [comment]
It is active, see attached screen capture of the settings. Could it be something related to issue #16?

![OpenID Authentication Plugin Settings](https://user-images.githubusercontent.com/93642234/140508226-6776ef3b-ac6e-4203-a2c2-edcabc949948.PNG)
