### ISSUE TITLE
Cannot configure extension

### ISSUE THREAD

**Issue by frafra** [leibniz-psychology/openid#20]
**Describe the bug**
Cannot configure extension after installation.

**To Reproduce**
1. Install the latest stable release by uploading the tarball
2. Activate the extension
3. Click on configure

**What application are you using?**
 OJS 3.3.0.7 dockerized (pkpofficial/ojs:3_3_0-4).

**Additional information**
![image](https://user-images.githubusercontent.com/4068/157449175-889f19a1-a9d8-4ac5-a282-b658fbda700d.png)
```
[Wed Mar 09 14:18:58.665827 2022] [php7:error] [pid 9] [client 158.38.174.15:43198] PHP Parse error:  syntax error, unexpected 'OpenIDPlugin' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /var/www/html/plugins/generic/openid/forms/OpenIDPluginSettingsForm.inc.php on line 41, referer: https://ojs-demo.nina.no/index.php/test/management/settings/website?r=6228a72bd960a
```

**Comment by frafra** [comment]
Sorry, I just took the latest release.
I am now able to see the configuration, even if the interface still have some kind of templating issue:
![image](https://user-images.githubusercontent.com/4068/157467711-ce4fe6b2-2f05-490b-856d-fb7e21177fae.png)

**Comment by RBoelter** [comment]
This looks like a translation problem. What language are you using in your OJS. You can find all supported languages for this plugin here: https://translate.pkp.sfu.ca/projects/plugins/openid/

**Comment by frafra** [comment]
You are right, the plugin has not been translated. I would have expected some English text instead of placeholders :) I am going to translate it in Norwegian.
