### ISSUE TITLE
Unable to log in via ORCID

### ISSUE THREAD

**Issue by felixhelix** [leibniz-psychology/openid#26]
### Discussed in https://github.com/leibniz-psychology/openid/discussions/25

<div type='discussions-op-text'>

<sup>Originally posted by **felixhelix** June 24, 2022</sup>
Hi,
I'm testing the ORCID integration of OJS and want to publish a detailed description for our journal editors.
I was able to register with my ORCID account. But when I log out and try to log in again via ORCID, I am always redirected to the page asking 

" Do you already have an account with Journal of XY?
-Yes, I already have an account.
-No, I'm new to Journal of XY!."

However, if I choose "Yes" I need a valid OJS account with password.

: (

If  the user already exists, and so "Yes" is a valid option, the account is successfully connected to ORCID. In the following I can log in using my ORCID credentials.

Any ideas?

Your's
Felix

OJS 3.1.2.0
OpenID 3.3.0.6</div>

**Comment by nmueller18** [comment]
From your last two lines, it seems that your are trying the wrong plugin-version with your OJS. You need [this](https://github.com/leibniz-psychology/openid/releases/download/v3_1_0-3/openid-v3_1_0-3.tar.gz).

**Comment by RBoelter** [comment]
Did you install the plugin via the plugin gallery, or did you upload the zip file to your OJS?

**Comment by felixhelix** [comment]
As far as I remember I installed the plugin via the gallery. 
Is there a difference in the code or database to look for?

**Comment by RBoelter** [comment]
I asked because I was wondering why you are using the plugin version 3.3.0.6, because there is a newer version.
https://github.com/leibniz-psychology/openid/releases/tag/v3_3_0-7

It seems there is an error in the plugin gallery, because OpenId version 3.3.0.6 supports OJS 3.3.0.1 -> 3.3.0.11, but OpenId 3.3.0.7 supports only 3.3.0.1 -> 3.3.0.3. I will ask the PKP staff on Monday if there is a reason for this or if it's just a glitch.

Maybe it already fixes your problem if you install the most recent version ([openid-v3_3_0-7.tar.gz](https://github.com/leibniz-psychology/openid/releases/download/v3_3_0-7/openid-v3_3_0-7.tar.gz).) manually

**Comment by felixhelix** [comment]
Thanks @RBoelter!
I tried to manually update the plugin, but got the following error message:

`[Mon Jul 04 10:52:22.077021 2022] [php7:error] [pid 14875] [client 134.95.147.149:33804] PHP Fatal error:  Uncaught Error: Call to a member function getFilePath() on null in /var/www/html/lib/pkp/controllers/grid/plugins/form/UploadPluginForm.inc.php:83\nStack trace:\n#0 /var/www/html/lib/pkp/classes/controllers/grid/plugins/PluginGridHandler.inc.php(334): UploadPluginForm->execute()\n#1 /var/www/html/lib/pkp/classes/core/PKPRouter.inc.php(395): PluginGridHandler->saveUploadPlugin(Array, Object(Request))\n#2 /var/www/html/lib/pkp/classes/core/PKPComponentRouter.inc.php(257): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array)\n#3 /var/www/html/lib/pkp/classes/core/Dispatcher.inc.php(144): PKPComponentRouter->route(Object(Request))\n#4 /var/www/html/lib/pkp/classes/core/PKPApplication.inc.php(362): Dispatcher->dispatch(Object(Request))\n#5 /var/www/html/index.php(68): PKPApplication->execute()\n#6 {main}\n\nNext Error: Call to a member function getId() on null in /var/www/html/lib/pkp/controllers/grid/plugins/form/UploadPluginForm.inc.php:88\nStack trace:\n#0 /var/www/html/lib/pkp/classes/controllers/g in /var/www/html/lib/pkp/controllers/grid/plugins/form/UploadPluginForm.inc.php on line 88`

Is this related to the plugin or is this an ojs/pkp issue?

**Comment by RBoelter** [comment]
It is a PKP error, but I do not know why it occurs.
I guess the line where the error occurs is: 
```php 
$temporaryFileManager->deleteById($temporaryFile->getId(), $user->getId());
```
This means that the `$temporaryFile` is null, because the error is `Call to a member function getId() on null` and the user cannot be null, because you are logged in.
It could be a problem with the write permission of the /plugins folder.

**Comment by felixhelix** [comment]
I had to delete the older version, as OJS kept telling me that the installed version (3.3.0.6) was as new or newer than 3.3.0.7? 
As far as I can see, the entries in version.xml are O.K..
Maybe this is connected to the fact that in the gallery also the 3.3.0.6 version is given as the latest version?

**Comment by felixhelix** [comment]
The problem still occurs, even when using the newest version of the plugin (3.3.0.7).

I noted that in the user profile under "public" after registration it says "The ORCID is automatically provided by your authenticated ORCID account". However, when I log in to this user's account later via admin "login as", no ORCID is set.

**Comment by RBoelter** [comment]
I checked the plugin yesterday and everything worked. Are there any errors in the error.log caused by this plugin?

**Comment by felixhelix** [comment]
@RBoelter, thanks for checking!

I found the following warning in the error.log:

`PHP Warning:  array_shift() expects parameter 1 to be array, object given in /var/www/html/lib/pkp/classes/core/PKPRouter.inc.php on line 485, referer: https://journals.xxx..de/index.php/journalname/openid/doAuthentication?provider=orcid&code=xxx
`

Also I noted that despite the note that the ORCID is automatically provided, there is still the option to connect an ORCID:

![image](https://user-images.githubusercontent.com/5220783/180413636-d739cff6-3ca8-47f3-a07a-e8ed7a311ff1.png)

And I get the same PHP warning as cited above for /user/profile.

**Comment by RBoelter** [comment]
Do you use this OpenID Plugin and the [OrcidProfile](https://github.com/pkp/orcidProfile) Plugin in your OJS? If so, this could be the problem, because the "[Create or Connect your ORCID ID](https://docs.pkp.sfu.ca/orcid/en/using-plugin)" button is part of the OrcidProfile plugin. It seems that using both plugins has some undesirable side effects.

**Comment by felixhelix** [comment]
Yes, we use the profile plugin as well. So I deactivated it and tried it again:

![image](https://user-images.githubusercontent.com/5220783/180439934-1385e971-3962-4fed-942b-146e3fea0877.png)

Still, I f I log out and try to log in again, the same happens : (

Also, as can be seen above, the ORCID is not given in the respective field.
If the OrcidProfile plugin was activated, I could connect my ORCID and then log in successfully via ORCID. So this way both plugins work together. It seems that in our case the flow from the openID plugin to the OrcidProfile does not work as it should.

**Comment by felixhelix** [comment]
@RBoelter Any ideas concerning the issue?
Yours Felix

**Comment by felixhelix** [comment]
Hi @RBoelter, 

I digged into the plugin and found that - at least for ORCID - in my case the ORCID ID in user_setting openid::orcid was not saved when a user registered via ORCID. 
Checking the code I noticed a difference in the file forms\OpenIDStep2Form.inc.php between the last release 3.3.0.7 (which we use on the server) and the latest code (which I forked): There is a code block added (from line 229 on). which inserts the orcid id in the user_profile table. I updated the file and that solved our problem : )
If you could publish a new release with the corrected files this would be great.
This seems to be related to the issue #15,  issue #16, and issue #18 

Yours Felix
