### ISSUE TITLE
Unable to save OpenID provider setting for OJS 3.3.0.11

### ISSUE THREAD

**Issue by lynsalcedo** [leibniz-psychology/openid#27]
I entered the info for Microsoft Azure Active Directory under OpenID provider and clicked OK but my entries are not saved.  I also tried the other providers but did not work as well.  Settings for Advanced plugin functions are saving though.  Thank you very much for looking into this.  By the way, our OJS is hosted on Windows Server 2019.

**Comment by MarkJaroski** [comment]
Hi, I'm a colleague of Lynn's.

When I test this I get the same result. I'm 100% sure that the data is being POSTed to the Apache2.4 on Win2019 server correctly. Here's the redacted POST data:

`
csrfToken: 1d9083d5a6c1654bf0a90d7d0618436e
provider[custom][active]: 1
provider[custom][configUrl]: https://login.microsoftonline.com/f610c0b7-bd24-4b39-810b-3dc280afb590/v2.0/.well-known/openid-configuration
provider[custom][btnImg]: 
provider[custom][btnTxt][en_US]: Sign in with WHO
provider[custom][clientId]: 9d3be1dc-b2d3-4cbe-876c-6433ac494ebd
provider[custom][clientSecret]: *REDACTED*
provider[orcid][configUrl]: https://orcid.org/.well-known/openid-configuration
provider[orcid][clientId]: 
provider[orcid][clientSecret]: 
provider[google][configUrl]: https://accounts.google.com/.well-known/openid-configuration
provider[google][clientId]: 
provider[google][clientSecret]: 
provider[microsoft][configUrl]: https://login.windows.net/common/.well-known/openid-configuration
provider[microsoft][clientId]: 
provider[microsoft][clientSecret]: 
provider[apple][configUrl]: https://appleid.apple.com/.well-known/openid-configuration
provider[apple][clientId]: 
provider[apple][clientSecret]: 
legacyLogin: 1
providerSync: 1
disableFields[givenName]: 1
disableFields[familyName]: 1
disableFields[email]: 1
hashSecret: M#(s@OUyG6&66(hQuS9AGC2d6b6CTEvRJ&R0ir%C/i2m
generateAPIKey: 1
submitFormButton: 
`
Later the openid file in the cache folder exists, but it contains none of this data.

**Comment by MarkJaroski** [comment]
Indeed. We have this:

` Uncaught GuzzleHttp\\Exception\\RequestException: cURL error 77: error setting certificate verify locations:`

I'll see if I can debug that.

**Comment by RBoelter** [comment]
maybe this helps: https://stackoverflow.com/questions/55204210/curl-error-77-error-setting-certificate-verify-locations-cafile

**Comment by MarkJaroski** [comment]
Yes, I downloaded a copy of cacerts.pem from the cURL website, and set it in the local config as well as the machine-level php.ini. We're all good now. Thank you @lynsalcedo, let's close this.
