### ISSUE TITLE
Upgrade the compatibility with OJS 3.4.0.3

### ISSUE THREAD

**Issue by ShubashBiswas** [leibniz-psychology/openid#34]
**Describe the problem you would like to solve**
Example: Our editors need a way to use the plugin but as it's not compatible with ojs 3.4 we cannot use the plugin. 

**Describe the solution you'd like**
Please tell us how you would like this solution to be solved.

**Who is asking for this feature?**
Users are requesting this feature. Examples: Journal Editors, Journal Administrators, Technical Support, Authors, Reviewers, etc.

**Additional information**
N/A

**Comment by mpbraendle** [comment]
Can't confirm - it is working with OJS 3.4. Please install the plugin from the plugin gallery (version 4.0.0).
