### ISSUE TITLE
I can't setting plugin page.

### ISSUE THREAD

**Issue by OhnO395** [leibniz-psychology/openid#7]
**Describe the bug**
I use ojs3.2.1-4 and open 2 journal.
I can't setting administrator -> Site Settings-> plugins page.
![image](https://user-images.githubusercontent.com/3378704/124894574-fd0edc80-e005-11eb-90b3-eaf15e975bbb.png)

php error  "PHP Fatal error:  Uncaught Error: Call to a member function getId() on null in /app/plugins/generic/openid/OpenIDPlugin.inc.php"

If i remove openid, i can setting administrator -> Site Settings-> plugins page.

**Additional information**
i use openid version = https://github.com/leibniz-psychology/openid/releases/tag/v3_2_0-5

**Comment by RBoelter** [comment]
Hello,
thanks for reporting. 
It seems that the problem is `$request->getContext()->getId()` because the plugin is not configurable site-wide.
I released a fix: https://github.com/leibniz-psychology/openid/releases/tag/v3_2_0-6
The plugin is still not configurable under `Administration -> Site Settings-> Plugins`, but the PHP error should be gone. 
You have to go to  `<Your Journal> -> Settings -> Website -> Plugins` to set/edit the plugin settings.

**Comment by OhnO395** [comment]
thank you. how to disable it, if administrator.
![image](https://user-images.githubusercontent.com/3378704/124946388-301e9380-e039-11eb-85c6-b575e690eca6.png)

**Comment by OhnO395** [comment]
I am test before if not context (admin site). in OpenIDPlugin.inc.php

if($request->getContext() == null) $conId = 0; else $conId = $request->getContext()->getId();

I will can disble openid plugin.

**Comment by RBoelter** [comment]
I uploaded a wrong tar.gz file, https://github.com/leibniz-psychology/openid/releases/tag/v3_2_0-7 should now solve your problem.
I also added:
https://github.com/leibniz-psychology/openid/blob/bb96395aa27c5868661adb5a6863fa85fa1c3d70/OpenIDPlugin.inc.php#L69-L74

And I added:
https://github.com/leibniz-psychology/openid/blob/bb96395aa27c5868661adb5a6863fa85fa1c3d70/OpenIDPlugin.inc.php#L32-L35
which should disable the plugin on `Administration -> Site Settings-> Plugins`

**Comment by OhnO395** [comment]
> I uploaded a wrong tar.gz file, https://github.com/leibniz-psychology/openid/releases/tag/v3_2_0-7 should now solve your problem.
> I also added:
> https://github.com/leibniz-psychology/openid/blob/bb96395aa27c5868661adb5a6863fa85fa1c3d70/OpenIDPlugin.inc.php#L69-L74
> 
thank you.

**Comment by OhnO395** [comment]
> I uploaded a wrong tar.gz file, https://github.com/leibniz-psychology/openid/releases/tag/v3_2_0-7 should now solve your problem.
> I also added:
> https://github.com/leibniz-psychology/openid/blob/bb96395aa27c5868661adb5a6863fa85fa1c3d70/OpenIDPlugin.inc.php#L69-L74
> 
> And I added:
> https://github.com/leibniz-psychology/openid/blob/bb96395aa27c5868661adb5a6863fa85fa1c3d70/OpenIDPlugin.inc.php#L32-L35
> 
> 
> which should disable the plugin on `Administration -> Site Settings-> Plugins`

**Comment by OhnO395** [comment]
> And I added:
> https://github.com/leibniz-psychology/openid/blob/bb96395aa27c5868661adb5a6863fa85fa1c3d70/OpenIDPlugin.inc.php#L32-L35
> 
> 
> which should disable the plugin on `Administration -> Site Settings-> Plugins`

I add code in my site but openid plugin can check/checked  (Administration -> Site Settings-> Plugins)
![image](https://user-images.githubusercontent.com/3378704/125229829-bec53600-e301-11eb-9bef-fda95866c0e1.png)
